### ISSUE TITLE
Says the email is sent but no one is receiving 

### ISSUE THREAD

**Issue by sdb1228** [gmailgem/gmail#177]
I have been trying to use the example to send a simple email to myself and to my SO and it seems that it completes the sending but the email is never sent. Do I need to have my own SMTP server? I also set up  my account to accept less secure apps, but with no luck still.  Here is my code if it helps.

require 'gmail'

username = "username@gmail.com"
password = "password"
Gmail.connect(username, password) do |gmail|
	gmail.deliver do
	  to "to@gmail.com"	  
	  subject "Having fun in Puerto Rico!"
	  text_part do
	    body "Text of plaintext message."
	  end
	end
	puts gmail.logged_in?
	puts"sent"
end

**Comment by johnnyshields** [comment]
I do not use this gem to send mails. Can anyone else assist with this?

**Comment by amoludage** [comment]
Hello @sdb1228 

Please use `deliver!` method instead of `deliver` which  `raise_error` if something wrong, if you use `deliver` method it gives `false` response if something not able to deliver.

Please try this, 


`    require 'gmail'

    username = "username@gmail.com"
    password = "password"

    Gmail.connect(username, password) do |gmail|
        mail = gmail.deliver do
            to "to@gmail.com"

            subject "Having fun in Puerto Rico!"
            text_part do
                body "Text of plaintext message."
            end
        end
      puts mail
      puts gmail.logged_in?
      puts "sent"
end `

The `puts mail` will return the status of deliver method.
If returns `true` the mail is deliver to the recipient and if it returns `false` then something is wrong with parameters.

If you want to see `error` please use `deliver!` instead of `deliver`.

**Comment by johnnyshields** [comment]
Thanks @amoludage. @sdb1228 please reopen issue if this doesn't answer your question.
